Feature/select
likethearms/releox-react pull request #102
Opened 2019-09-20 09:45 UTC by eetlaa

2019-09-20 10:55 UTC, likethearms requested changes
NativeSelect component nimea ei voi kayttaa, koska se ei ole natiivi ja paketista puuttuu Formik versio inputista ja Readme.md.

- [x] Update README.md
- [x] Formik Select
- [x] NativeSelect rename

2019-10-03 15:27 UTC, likethearms commented on README.md
> +  > > > > > > > origin/1.1.0
Merge conflict mukaan? :D

2019-10-03 15:35 UTC, likethearms requested changes
Noi merge conflict vois ottaa pois

2019-10-03 15:45 UTC, likethearms commented on src/components/ReactSelect/ReactSelect.tsx
> +  options: any[];
Options ei voi olla any

2019-10-03 15:46 UTC, likethearms commented on src/components/ReactSelect/ReactSelect.tsx
> +  onChange(value: any): void;
Formikissa ei voi kayttaa onChangee

2019-10-03 15:46 UTC, likethearms requested changes
Loysin vie muutaman lisa ongelman

2019-10-03 15:47 UTC, likethearms commented on src/components/ReactSelect/ReactSelect.tsx
> +  selectedOption?: any;
Formikissa ei voi olla myoskaan komponentin ulkopuolelta tulevaa selectedOptionsia

2019-10-03 15:49 UTC, likethearms commented on src/components/ReactSelect/ReactSelect.tsx
> +          value={selectedOption || null}
Value taytyy tulle tuolta Formik bagista ja eika sit tarvi ORittaa nulliks

2019-10-03 15:49 UTC, likethearms requested changes
ja vie loyty pari

2019-10-03 18:01 UTC, eetlaa commented on src/components/ReactSelect/ReactSelect.tsx
> +          value={selectedOption || null}
value={fieldProps.field.value}

tahan tapaan vai

2019-10-03 21:21 UTC, likethearms approved these changes

2019-10-03 21:21 UTC, merged